# SQL queries.
INSERT_BA = "INSERT INTO BID_ASK_HISTORY (DATETIME, REQ_TYPE, PRICE) VALUES ({timestamp}, {req_type}, {price}"
FETCH_LAST_FIVE = "SELECT * FROM BID_ASK_HISTORY WHERE REQ_TYPE='{}' ORDER BY DATETIME DESC LIMIT {}"
